# Generated by Django 5.1.6 on 2025-03-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='fullname',
            field=models.CharField(max_length=255),
        ),
    ]
